# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/addRelation.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addRelation(object):
    def setupUi(self, addRelation):
        addRelation.setObjectName("addRelation")
        addRelation.resize(341, 201)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(addRelation.sizePolicy().hasHeightForWidth())
        addRelation.setSizePolicy(sizePolicy)
        addRelation.setMinimumSize(QtCore.QSize(341, 201))
        addRelation.setMaximumSize(QtCore.QSize(341, 201))
        addRelation.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addRelation.setWindowIcon(icon)
        addRelation.setToolTip("")
        addRelation.setStyleSheet("background: rgb(54, 57, 63);\n"
"color: rgb(255, 255, 255)")
        self.characterList = QtWidgets.QListWidget(addRelation)
        self.characterList.setGeometry(QtCore.QRect(10, 70, 161, 121))
        self.characterList.setStyleSheet("QListWidget{\n"
"    color: rgb(255, 255, 255);\n"
"    background: rgb(64, 68, 75);\n"
"    border: 1px solid rgb(50, 50, 50);\n"
"    border-radius:5px;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QListWidget:item{\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left: 3px;\n"
"    padding-right: 3px;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget:item:hover{\n"
"    padding-left: 3px;\n"
"    padding-right: 3px;\n"
"    background: rgb(74, 76, 79);\n"
"    border: 1px solid rgb(64, 66, 75);\n"
"}\n"
"\n"
"QListWidget:item:selected{\n"
"    padding-left: 3px;\n"
"    padding-right: 3px;\n"
"    background: rgb(93, 94, 97);\n"
"    border: 1px solid rgb(74, 76, 79);\n"
"}")
        self.characterList.setIconSize(QtCore.QSize(11, 11))
        self.characterList.setObjectName("characterList")
        self.accept = QtWidgets.QPushButton(addRelation)
        self.accept.setEnabled(False)
        self.accept.setGeometry(QtCore.QRect(180, 170, 71, 23))
        self.accept.setStyleSheet("QPushButton {\n"
"    background: rgb(64, 68, 75);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(79, 83, 89);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: rgb(54, 57, 63);\n"
"    color: rgb(126, 126, 126);\n"
"}")
        self.accept.setObjectName("accept")
        self.label = QtWidgets.QLabel(addRelation)
        self.label.setGeometry(QtCore.QRect(10, 4, 152, 31))
        self.label.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"}")
        self.label.setObjectName("label")
        self.relationType = QtWidgets.QListWidget(addRelation)
        self.relationType.setGeometry(QtCore.QRect(180, 70, 151, 91))
        self.relationType.setStyleSheet("QListWidget{\n"
"    color: rgb(255, 255, 255);\n"
"    background: rgb(64, 68, 75);\n"
"    border: 1px solid rgb(50, 50, 50);\n"
"    border-radius:5px;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QListWidget:item{\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left: 3px;\n"
"    padding-right: 3px;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget:item:hover{\n"
"    padding-left: 3px;\n"
"    padding-right: 3px;\n"
"    background: rgb(74, 76, 79);\n"
"    border: 1px solid rgb(64, 66, 75);\n"
"}\n"
"\n"
"QListWidget:item:selected{\n"
"    padding-left: 3px;\n"
"    padding-right: 3px;\n"
"    background: rgb(93, 94, 97);\n"
"    border: 1px solid rgb(74, 76, 79);\n"
"}")
        self.relationType.setObjectName("relationType")
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.relationType.addItem(item)
        self.cancel = QtWidgets.QPushButton(addRelation)
        self.cancel.setGeometry(QtCore.QRect(260, 170, 71, 23))
        self.cancel.setStyleSheet("QPushButton {\n"
"    background: rgb(64, 68, 75);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(79, 83, 89);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: rgb(54, 57, 63);\n"
"    color: rgb(126, 126, 126);\n"
"}")
        self.cancel.setObjectName("cancel")
        self.search = QtWidgets.QLineEdit(addRelation)
        self.search.setGeometry(QtCore.QRect(10, 40, 161, 21))
        self.search.setAcceptDrops(False)
        self.search.setToolTip("")
        self.search.setStyleSheet("QLineEdit{\n"
"    background: rgb(64, 68, 75);\n"
"    border: 1px solid rgb(50, 50, 50);\n"
"    border-radius:5px;\n"
"    padding-left: 3px;\n"
"    padding-right: 3px;\n"
"}")
        self.search.setText("")
        self.search.setObjectName("search")
        self.searchRelation = QtWidgets.QLineEdit(addRelation)
        self.searchRelation.setGeometry(QtCore.QRect(180, 40, 151, 21))
        self.searchRelation.setAcceptDrops(False)
        self.searchRelation.setToolTip("")
        self.searchRelation.setStyleSheet("QLineEdit{\n"
"    background: rgb(64, 68, 75);\n"
"    border: 1px solid rgb(50, 50, 50);\n"
"    border-radius:5px;\n"
"    padding-left: 3px;\n"
"    padding-right: 3px;\n"
"}")
        self.searchRelation.setText("")
        self.searchRelation.setObjectName("searchRelation")
        self.label.setBuddy(self.characterList)

        self.retranslateUi(addRelation)
        self.cancel.clicked.connect(addRelation.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addRelation)
        addRelation.setTabOrder(self.characterList, self.relationType)
        addRelation.setTabOrder(self.relationType, self.accept)
        addRelation.setTabOrder(self.accept, self.cancel)

    def retranslateUi(self, addRelation):
        _translate = QtCore.QCoreApplication.translate
        self.accept.setText(_translate("addRelation", "Accept"))
        self.label.setText(_translate("addRelation", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Add Relation</span></p><p><br/></p></body></html>"))
        __sortingEnabled = self.relationType.isSortingEnabled()
        self.relationType.setSortingEnabled(False)
        item = self.relationType.item(0)
        item.setText(_translate("addRelation", "Father"))
        item = self.relationType.item(1)
        item.setText(_translate("addRelation", "Mother"))
        item = self.relationType.item(2)
        item.setText(_translate("addRelation", "Son"))
        item = self.relationType.item(3)
        item.setText(_translate("addRelation", "Daughter"))
        item = self.relationType.item(4)
        item.setText(_translate("addRelation", "Brother"))
        item = self.relationType.item(5)
        item.setText(_translate("addRelation", "Sister"))
        item = self.relationType.item(6)
        item.setText(_translate("addRelation", "Uncle"))
        item = self.relationType.item(7)
        item.setText(_translate("addRelation", "Aunt"))
        item = self.relationType.item(8)
        item.setText(_translate("addRelation", "Nephew"))
        item = self.relationType.item(9)
        item.setText(_translate("addRelation", "Niece"))
        item = self.relationType.item(10)
        item.setText(_translate("addRelation", "Boyfriend"))
        item = self.relationType.item(11)
        item.setText(_translate("addRelation", "Girlfriend"))
        item = self.relationType.item(12)
        item.setText(_translate("addRelation", "Fiancé"))
        item = self.relationType.item(13)
        item.setText(_translate("addRelation", "Husband"))
        item = self.relationType.item(14)
        item.setText(_translate("addRelation", "Wife"))
        self.relationType.setSortingEnabled(__sortingEnabled)
        self.cancel.setText(_translate("addRelation", "Cancel"))
        self.search.setWhatsThis(_translate("addRelation", "<html><head/><body><p><br/></p></body></html>"))
        self.search.setPlaceholderText(_translate("addRelation", "Search Characters"))
        self.searchRelation.setWhatsThis(_translate("addRelation", "<html><head/><body><p><br/></p></body></html>"))
        self.searchRelation.setPlaceholderText(_translate("addRelation", "Search Relations"))
