# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/options.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets

def resource_path(relative_path):
	""" Get absolute path to resource, works for dev and for PyInstaller """
	base_path = getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)));
	return os.path.join(base_path, relative_path);


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(191, 120)
        Dialog.setMinimumSize(QtCore.QSize(191, 120))
        Dialog.setMaximumSize(QtCore.QSize(191, 120))
        Dialog.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("icons/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background: rgb(54, 57, 63);\n"
"color: rgb(255, 255, 255)")
        self.acceptCancel = QtWidgets.QDialogButtonBox(Dialog)
        self.acceptCancel.setGeometry(QtCore.QRect(20, 80, 151, 32))
        self.acceptCancel.setStyleSheet("QPushButton {\n"
"    background: rgb(64, 68, 75);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(79, 83, 89);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: rgb(54, 57, 63);\n"
"    color: rgb(126, 126, 126);\n"
"}")
        self.acceptCancel.setOrientation(QtCore.Qt.Horizontal)
        self.acceptCancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.acceptCancel.setObjectName("acceptCancel")
        self.themeBox = QtWidgets.QComboBox(Dialog)
        self.themeBox.setGeometry(QtCore.QRect(93, 10, 69, 22))
        self.themeBox.setStyleSheet("background: rgb(64, 68, 75);\n"
"border: 1px solid rgb(50, 50, 50);\n"
"border-radius:5px;")
        self.themeBox.setObjectName("themeBox")
        self.themeBox.addItem("")
        self.themeBox.addItem("")
        self.themeLabel = QtWidgets.QLabel(Dialog)
        self.themeLabel.setGeometry(QtCore.QRect(31, 13, 47, 16))
        self.themeLabel.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"}")
        self.themeLabel.setObjectName("themeLabel")
        self.themeLabel.setBuddy(self.themeBox)

        self.retranslateUi(Dialog)
        self.acceptCancel.rejected.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.themeBox.setItemText(0, _translate("Dialog", "Dark"))
        self.themeBox.setItemText(1, _translate("Dialog", "Light"))
        self.themeLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Theme:</span></p></body></html>"))
