# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/events.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(511, 311)
        Form.setMinimumSize(QtCore.QSize(511, 311))
        Form.setMaximumSize(QtCore.QSize(511, 311))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.accept = QtWidgets.QPushButton(Form)
        self.accept.setEnabled(False)
        self.accept.setGeometry(QtCore.QRect(350, 280, 71, 23))
        self.accept.setObjectName("accept")
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setGeometry(QtCore.QRect(430, 280, 71, 23))
        self.cancel.setObjectName("cancel")
        self.textEditor = QtWidgets.QTextEdit(Form)
        self.textEditor.setGeometry(QtCore.QRect(10, 40, 491, 231))
        self.textEditor.setAcceptDrops(False)
        self.textEditor.setObjectName("textEditor")
        self.yearSpin = QtWidgets.QSpinBox(Form)
        self.yearSpin.setGeometry(QtCore.QRect(40, 280, 51, 22))
        self.yearSpin.setMaximum(10)
        self.yearSpin.setObjectName("yearSpin")
        self.monthSpin = QtWidgets.QSpinBox(Form)
        self.monthSpin.setGeometry(QtCore.QRect(150, 280, 51, 22))
        self.monthSpin.setMaximum(12)
        self.monthSpin.setObjectName("monthSpin")
        self.addToTimeline = QtWidgets.QCheckBox(Form)
        self.addToTimeline.setGeometry(QtCore.QRect(220, 281, 111, 20))
        self.addToTimeline.setObjectName("addToTimeline")
        self.yearLabel = QtWidgets.QLabel(Form)
        self.yearLabel.setGeometry(QtCore.QRect(11, 280, 51, 21))
        self.yearLabel.setObjectName("yearLabel")
        self.monthLabel = QtWidgets.QLabel(Form)
        self.monthLabel.setGeometry(QtCore.QRect(110, 280, 51, 21))
        self.monthLabel.setObjectName("monthLabel")
        self.worldBuildingLabel = QtWidgets.QLabel(Form)
        self.worldBuildingLabel.setGeometry(QtCore.QRect(10, 5, 151, 31))
        self.worldBuildingLabel.setObjectName("worldBuildingLabel")
        self.worldBuildingSearch = QtWidgets.QLineEdit(Form)
        self.worldBuildingSearch.setGeometry(QtCore.QRect(300, 10, 201, 21))
        self.worldBuildingSearch.setAcceptDrops(False)
        self.worldBuildingSearch.setToolTip("")
        self.worldBuildingSearch.setObjectName("worldBuildingSearch")
        self.eventTitle = QtWidgets.QLabel(Form)
        self.eventTitle.setGeometry(QtCore.QRect(220, 10, 81, 21))
        self.eventTitle.setObjectName("eventTitle")
        self.yearLabel.setBuddy(self.yearSpin)
        self.monthLabel.setBuddy(self.monthSpin)
        self.worldBuildingLabel.setBuddy(self.textEditor)
        self.eventTitle.setBuddy(self.worldBuildingSearch)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add Event"))
        self.accept.setText(_translate("Form", "Accept"))
        self.cancel.setText(_translate("Form", "Cancel"))
        self.textEditor.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.textEditor.setPlaceholderText(_translate("Form", "Type here..."))
        self.addToTimeline.setText(_translate("Form", "Add to Timeline?"))
        self.yearLabel.setText(_translate("Form", "Year"))
        self.monthLabel.setText(_translate("Form", "Month"))
        self.worldBuildingLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Add Event</span></p></body></html>"))
        self.worldBuildingSearch.setPlaceholderText(_translate("Form", "eg. Civil War"))
        self.eventTitle.setText(_translate("Form", "Title of Event"))
