# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/events.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# type: ignore
import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets

def resource_path(relative_path):
	""" Get absolute path to resource, works for dev and for PyInstaller """
	base_path = getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)));
	return os.path.join(base_path, relative_path);


class Ui_eventWindow(object):
    def setupUi(self, eventWindow):
        eventWindow.setObjectName("eventWindow")
        eventWindow.resize(511, 311)
        eventWindow.setMinimumSize(QtCore.QSize(511, 311))
        eventWindow.setMaximumSize(QtCore.QSize(511, 311))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("icons/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        eventWindow.setWindowIcon(icon)
        self.accept = QtWidgets.QPushButton(eventWindow)
        self.accept.setEnabled(False)
        self.accept.setGeometry(QtCore.QRect(350, 280, 71, 23))
        self.accept.setObjectName("accept")
        self.cancel = QtWidgets.QPushButton(eventWindow)
        self.cancel.setGeometry(QtCore.QRect(430, 280, 71, 23))
        self.cancel.setObjectName("cancel")
        self.textEditor = QtWidgets.QTextEdit(eventWindow)
        self.textEditor.setGeometry(QtCore.QRect(10, 40, 491, 231))
        self.textEditor.setAcceptDrops(False)
        self.textEditor.setObjectName("textEditor")
        self.yearSpin = QtWidgets.QSpinBox(eventWindow)
        self.yearSpin.setGeometry(QtCore.QRect(43, 280, 51, 22))
        self.yearSpin.setMaximum(9999)
        self.yearSpin.setObjectName("yearSpin")
        self.monthSpin = QtWidgets.QSpinBox(eventWindow)
        self.monthSpin.setGeometry(QtCore.QRect(143, 280, 51, 22))
        self.monthSpin.setMinimum(1)
        self.monthSpin.setMaximum(12)
        self.monthSpin.setObjectName("monthSpin")
        self.addToTimeline = QtWidgets.QCheckBox(eventWindow)
        self.addToTimeline.setGeometry(QtCore.QRect(203, 281, 141, 20))
        self.addToTimeline.setObjectName("addToTimeline")
        self.yearLabel = QtWidgets.QLabel(eventWindow)
        self.yearLabel.setGeometry(QtCore.QRect(11, 280, 51, 21))
        self.yearLabel.setObjectName("yearLabel")
        self.monthLabel = QtWidgets.QLabel(eventWindow)
        self.monthLabel.setGeometry(QtCore.QRect(103, 280, 51, 21))
        self.monthLabel.setObjectName("monthLabel")
        self.eventLabel = QtWidgets.QLabel(eventWindow)
        self.eventLabel.setGeometry(QtCore.QRect(10, 5, 151, 31))
        self.eventLabel.setObjectName("eventLabel")
        self.eventName = QtWidgets.QLineEdit(eventWindow)
        self.eventName.setGeometry(QtCore.QRect(300, 10, 201, 21))
        self.eventName.setAcceptDrops(False)
        self.eventName.setToolTip("")
        self.eventName.setObjectName("eventName")
        self.eventTitle = QtWidgets.QLabel(eventWindow)
        self.eventTitle.setGeometry(QtCore.QRect(215, 10, 91, 21))
        self.eventTitle.setObjectName("eventTitle")
        self.yearLabel.setBuddy(self.yearSpin)
        self.monthLabel.setBuddy(self.monthSpin)
        self.eventLabel.setBuddy(self.textEditor)
        self.eventTitle.setBuddy(self.eventName)

        self.retranslateUi(eventWindow)
        QtCore.QMetaObject.connectSlotsByName(eventWindow)
        eventWindow.setTabOrder(self.eventName, self.textEditor)
        eventWindow.setTabOrder(self.textEditor, self.yearSpin)
        eventWindow.setTabOrder(self.yearSpin, self.monthSpin)
        eventWindow.setTabOrder(self.monthSpin, self.addToTimeline)
        eventWindow.setTabOrder(self.addToTimeline, self.accept)
        eventWindow.setTabOrder(self.accept, self.cancel)

    def retranslateUi(self, eventWindow):
        _translate = QtCore.QCoreApplication.translate
        eventWindow.setWindowTitle(_translate("eventWindow", "Add Event"))
        self.accept.setText(_translate("eventWindow", "Accept"))
        self.cancel.setText(_translate("eventWindow", "Cancel"))
        self.textEditor.setHtml(_translate("eventWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.textEditor.setPlaceholderText(_translate("eventWindow", "Type here..."))
        self.addToTimeline.setText(_translate("eventWindow", "On Timeline?"))
        self.yearLabel.setText(_translate("eventWindow", "Year"))
        self.monthLabel.setText(_translate("eventWindow", "Month"))
        self.eventLabel.setText(_translate("eventWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Add Event</span></p></body></html>"))
        self.eventName.setPlaceholderText(_translate("eventWindow", "eg. Civil War"))
        self.eventTitle.setText(_translate("eventWindow", "Event Title"))
