# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/worldBuilding.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets

def resource_path(relative_path):
	""" Get absolute path to resource, works for dev and for PyInstaller """
	base_path = getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)));
	return os.path.join(base_path, relative_path);


class Ui_worldBuildingUI(object):
    def setupUi(self, worldBuildingUI):
        worldBuildingUI.setObjectName("worldBuildingUI")
        worldBuildingUI.resize(481, 281)
        worldBuildingUI.setMinimumSize(QtCore.QSize(481, 281))
        worldBuildingUI.setMaximumSize(QtCore.QSize(481, 281))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("icons/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        worldBuildingUI.setWindowIcon(icon)
        worldBuildingUI.setStyleSheet("background: rgb(54, 57, 63);\n"
"color: rgb(255, 255, 255);")
        self.WorldBuildingLabel = QtWidgets.QLabel(worldBuildingUI)
        self.WorldBuildingLabel.setGeometry(QtCore.QRect(10, 5, 151, 31))
        self.WorldBuildingLabel.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    font: font \"Fira Code\";\n"
"}")
        self.WorldBuildingLabel.setObjectName("WorldBuildingLabel")
        self.accept = QtWidgets.QPushButton(worldBuildingUI)
        self.accept.setEnabled(False)
        self.accept.setGeometry(QtCore.QRect(320, 10, 71, 23))
        self.accept.setStyleSheet("QPushButton {\n"
"    background: rgb(64, 68, 75);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(79, 83, 89);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: rgb(54, 57, 63);\n"
"    color: rgb(126, 126, 126);\n"
"}")
        self.accept.setObjectName("accept")
        self.cancel = QtWidgets.QPushButton(worldBuildingUI)
        self.cancel.setGeometry(QtCore.QRect(400, 10, 71, 23))
        self.cancel.setStyleSheet("QPushButton {\n"
"    background: rgb(64, 68, 75);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(79, 83, 89);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: rgb(54, 57, 63);\n"
"    color: rgb(126, 126, 126);\n"
"}")
        self.cancel.setObjectName("cancel")
        self.textEditor = QtWidgets.QTextEdit(worldBuildingUI)
        self.textEditor.setGeometry(QtCore.QRect(10, 40, 461, 231))
        self.textEditor.setAcceptDrops(False)
        self.textEditor.setStyleSheet("QTextEdit {\n"
"    background: rgb(64, 68, 75);\n"
"    border: 1px solid rgb(50, 50, 50);\n"
"    border-radius:5px;\n"
"    padding: 3px;\n"
"}")
        self.textEditor.setPlaceholderText("")
        self.textEditor.setObjectName("textEditor")
        self.WorldBuildingLabel.setBuddy(self.textEditor)

        self.retranslateUi(worldBuildingUI)
        self.cancel.clicked.connect(worldBuildingUI.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(worldBuildingUI)

    def retranslateUi(self, worldBuildingUI):
        _translate = QtCore.QCoreApplication.translate
        worldBuildingUI.setWindowTitle(_translate("worldBuildingUI", "Add Detail"))
        self.WorldBuildingLabel.setText(_translate("worldBuildingUI", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Add Detail</span></p></body></html>"))
        self.accept.setText(_translate("worldBuildingUI", "Accept"))
        self.cancel.setText(_translate("worldBuildingUI", "Cancel"))
        self.textEditor.setHtml(_translate("worldBuildingUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
